name: Release

on:
  push:
    branches:
      - master

jobs:

  ci:
    name: CI
    uses: ponlawat-w/moodle-local_accessibility/.github/workflows/ci.yml@master
    with:
      widget-backgroundcolour-branch: ${{ github.ref }}

  get-version:
    name: Get version info
    uses: ponlawat-w/moodle-local_accessibility/.github/workflows/get-version.yml@master
    with:
      ref: ${{ github.ref }}

  release:
    name: Release
    needs: [ci, get-version]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Push to Branch
        run: |
          git checkout -b ${{ needs.get-version.outputs.branch-name }}
          git push -f -u origin ${{ needs.get-version.outputs.branch-name }}

      - name: Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}
          custom_tag: ${{ needs.get-version.outputs.plugin-release }}
          release_branches: ${{ github.ref_name }}

      - name: Relase
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ needs.get-version.outputs.plugin-release }}
          body: ${{ needs.get-version.outputs.plugin-release }} - ${{ needs.get-version.outputs.plugin-version }}
